---
title: "Age structured schistosomiasis model"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

devtools::load_all("../../DDNTD")

require(tidyverse)
```

# Age structured model  

```{r}
H = 300
area = 200

age_strat_pars <- c(
  ##standard snail parameters
    r=0.10,             # recruitment rate (from sokolow et al)
    K=50*area,          # carrying capacity corresponding to 50 snails per square meter
    mu_N=1/60,          # Mean mortality rate of snails (assuming lifespan of 60days)
    sigma=1/40,         # Transition rate from exposed to infected (assuming pre-patency period of 40 days)
    mu_I=1/10,          # Increased mortality rate of infected snails

  #Adult Worm, Miracidia and Cercariae Parameters
    mu_W = 1/(4*365), # death rate of adult worms
    m = 5.2,            # mean eggs shed per female worm per 10mL urine (truscott et al)

  #Density dependence parameters
    zeta = 5e-3,       # parameter of fecundity reduction function
    xi = 2.8e-3,        # parameter for acquired immunity function http://doi.wiley.com/10.1111/j.1365-3024.1992.tb00029.x

  #Human parameters
    H_TC = 120,         # Total number of treated children
    H_UC = 30,          # Total number of untreated children
    H_TA = 0,           # Total number of treated adults
    H_UA = 150,         # Total number of untreated adults
    U_C = 110,          # mL urine produced per child per day /10mL https://doi.org/10.1186/s13071-016-1681-4
    U_A = 130,          # mL urine produced per adult per day /10mL https://doi.org/10.1186/s13071-016-1681-4
    v = 0.08,           # mean egg viability (miracidia per egg)
    omega = 1.5,        # relative infection risk/contamination of SAC vs adults (related to sanitation/education/water contact)

  #Transmission parameters
    alpha=1.2e-4,       # Cercarial infection probability
    Lambda_0=1,         # first parameter of non-linear man-to-snail FOI
    beta=1.6e-4         # second parameter of non-linear man-to-snail FOI
)


schisto_age_strat_mod <- function(t, n, parameters) {
  #Parameter values
    r=parameters["r"]          # recruitment rate (from sokolow et al)
    K=parameters["K"]          # carrying capacity corresponding to 50 snails per square meter
    mu_N=parameters["mu_N"]       # Mean mortality rate of snails (assuming lifespan of 60days)
    sigma=parameters["sigma"]      # Transition rate from exposed to infected (assuming pre-patency period of 40 days)
    mu_I=parameters["mu_I"]       # Increased mortality rate of infected snails

  #Adult Worm, Miracidia and Cercariae Parameters
    mu_W = parameters["mu_W"]     # death rate of adult worms
    m = parameters["m"]              # mean eggs shed per female worm per 10mL urine (truscott et al)
    v = parameters["v"]             # mean egg viability of eggs shed into environment

  #Density dependence parameters
    zeta = parameters["gamma"]       # parameter of fecundity reduction function
    xi = parameters["xi"]        # parameter for acquired immunity funtion

  #Human parameters
    H = parameters["H"]              # Total number of people
    prop_SAC = parameters[""]     # Percent of people that are school age children (SAC)
    prop_adult = parameters   # percent of people that are not school age children (assumed here to be adults)
    cvrg_SAC = parameters     # MDA coverage in SAC population
    cvrg_adult = parameters     # MDA coverage in adult population
    u_SAC = parameters         # mL urine per SAC/day/10mL assumed to be half of adult (approximate, ranges from 20 - 100)
    u_adult = parameters      # mL urine per adult/day/10mL (approximate, ranges from 80 - 200)
    rho_SAC = parameters      # relative number of eggs shed by SAC that make it to snail habitat (~sanitation)
    rho_adult = parameters  # relative number of eggs shed by adults that make it to snail habitat (~sanitation); 5% of SAC (truscott et al)
    omega_SAC = parameters      # relative infection risk of SAC (related to clean water access/education/water contact)
    omega_adult = parameters  # relative infection risk of adults (related to clean water access/education/water contact)

  #Transmission parameters
    lambda=parameters      # snail-to-man transmission
    Lambda_0=parameters         # first parameter of non-linear man-to-snail FOI
    beta=parameters        # second parameter of non-linear man-to-snail FOI

  
  #State variables
    S=n[1]
    E=n[2]
    I=n[3]
    W_TC=n[4]
    W_UC=n[5]
    W_TA=n[6]
    W_UA=n[7]

    #Total snail population
      N=S+E+I

    #Update clumping parameter, k from estimate of worm burden in each population
      k_TC = k_from_log_W(W_TC)
      k_UC = k_from_log_W(W_UC)
      k_TA = k_from_log_W(W_TA)
      k_UA = k_from_log_W(W_UA)

    #Estimate mating probability within each strata
      phi_W_TC = phi_Wk(W = W_TC, k = k_TC)  #Mating probability in treated SAC population
      phi_W_UC = phi_Wk(W = W_UC, k = k_UC)  #Mating probability in untreated SAC population
      phi_W_TA = phi_Wk(W = W_TA, k = k_TA)  #Mating probability in treated adult population
      phi_W_UA = phi_Wk(W = W_UA, k = k_UA)  #Mating probability in untreated adult population


    #Estimate mean eggs produced per person in each strata as product of
      # mated female worms (0.5*worm burden*mating probability),
      # eggs produced per female worm per 10mL urine,
      # urine produced per day /10mL
      # and reduction in fecundity due to crowding
        eggs_W_TC = 0.5*(W_TC*phi_W_TC) * m * U_C * rho_Wk(W_TC, zeta, k_TC)
  
        eggs_W_UC = 0.5*(W_UC*phi_W_UC) * m * U_C * rho_Wk(W_UC, zeta, k_UC)
  
        eggs_W_TA = 0.5*(W_TA*phi_W_TA) * m * U_A * rho_Wk(W_TA, zeta, k_TA)
  
        eggs_W_UA = 0.5*(W_UA*phi_W_UA) * m * U_A * rho_Wk(W_UA, zeta, k_UA)

    #Estimate miracidia produced by each strata as product of
      # mean eggs per 10 mL urine for individuals in each strata,
      # number of people in each strata,
      # egg viability  
      # contamination coefficient for SAC/adults,

      M_W_TC = eggs_W_TC * v * H_TC * omega

      M_W_UC = eggs_W_UC * v * H_UC * omega

      M_W_TA = eggs_W_TA * v * H_TA 

      M_W_UA = eggs_W_UA * v * H_UA 

    # Estimate total miracidia entering snail habitat
      M_tot = M_W_TC + M_W_UC + M_W_TA + M_W_UA

    # Snail infection dynamics
      dSdt= r*(1-(N/K))*(S+E) - mu_N*S - Lambda_0*(1-exp(-beta*M_tot/N))*S #Susceptible snails

      dEdt= Lambda_0*(1-exp(-beta*M_tot/N))*S - (mu_N+sigma)*E #Exposed snails

      dIdt= sigma*E - mu_I*I #Infected snails

    # Estimate cercarial output from infected snail population
      C = theta*I
      
    #worm burden in human populations
      dW_TCdt= omega*alpha*C*gam_Wv(W_TC, xi) - (mu_W*W_TC)
      dW_UCdt= omega*alpha*C*gam_Wv(W_UC, xi) - (mu_W*W_UC)
      dW_TAdt= alpha*C*gam_Wv(W_TA, xi) - (mu_W*W_TA)
      dW_UAdt= alpha*C*gam_Wv(W_UA, xi) - (mu_W*W_UA)

    return(list(c(dSdt,dEdt,dIdt,
                  dW_TCdt,dW_UCdt,
                  dW_TAdt, dW_UAdt)))
}
```

```{r sim_age_structure}
years <- 20
age_time <- c(1:(365*years))

age_start <- c(S=5000, E=0, I=0, W_TC=10, W_UC=10, W_TA=10, W_UA=10)

#Run to equibrium with base parameter set
age_eqbm <- runsteady(y = age_start, func = schisto_age_strat_mod,
                      parms = age_strat_pars)[["y"]]

schisto_age_sim <- sim_schisto_mod(nstart = age_eqbm, 
                                   time = age_time, 
                                   model = schisto_age_strat_mod,
                                   parameters = age_strat_pars,
                                   events_df = NA)
```

## Simulate 10 years of annual MDA in 75% of SAC populaition  
```{r sim_mda_sac}
eff <- 0.93
age_strat_pars["cvrg_SAC"] <- 0.75

sac_mda <- data.frame(var = rep('W_TC', years/2),
                      time = c(1:(years/2))*365,
                      value = rep((1 - eff), years/2),
                      method = rep('mult', years/2))

schisto_mda_sim <- sim_schisto_mod(nstart = age_eqbm, 
                                   time = age_time, 
                                   model = schisto_age_strat_mod,
                                   parameters = age_strat_pars,
                                   events_df = sac_mda)

schisto_mda_sim %>% 
  gather("Treatment", "Worm Burden",  W_TC:W_UA) %>% 
  ggplot(aes(x = time, y = `Worm Burden`, lty = Treatment)) +
    geom_line() +
    theme_classic() +
    theme(legend.position = c(0.6,0.8)) +
    ylim(c(0,100)) +
    scale_x_continuous(breaks = c(0:years)*365,
                       labels = c(-1:(years-1)))
```

